/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileAccountRouteImport } from './routes/mobile.account'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalNoticeRouteImport } from './routes/legal.notice'
import { Route as ApiUserStatusRouteImport } from './routes/api/user-status'
import { Route as ApiTranslateAudioRouteImport } from './routes/api/translate-audio'
import { Route as ApiSubscriptionRouteImport } from './routes/api/subscription'
import { Route as ApiReadMessageRouteImport } from './routes/api/read-message'
import { Route as ApiMobileDialogRouteImport } from './routes/api/mobile-dialog'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiPublicTrackViewRouteImport } from './routes/api/public/track-view'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAccountRoute = MobileAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MobileRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal/notice',
  path: '/legal/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserStatusRoute = ApiUserStatusRouteImport.update({
  id: '/api/user-status',
  path: '/api/user-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateAudioRoute = ApiTranslateAudioRouteImport.update({
  id: '/api/translate-audio',
  path: '/api/translate-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadMessageRoute = ApiReadMessageRouteImport.update({
  id: '/api/read-message',
  path: '/api/read-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileDialogRoute = ApiMobileDialogRouteImport.update({
  id: '/api/mobile-dialog',
  path: '/api/mobile-dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackViewRoute = ApiPublicTrackViewRouteImport.update({
  id: '/api/public/track-view',
  path: '/api/public/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/mobile': typeof MobileRouteWithChildren
  '/pricing': typeof PricingRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/mobile-dialog': typeof ApiMobileDialogRoute
  '/api/read-message': typeof ApiReadMessageRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/translate-audio': typeof ApiTranslateAudioRoute
  '/api/user-status': typeof ApiUserStatusRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mobile/account': typeof MobileAccountRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/mobile': typeof MobileRouteWithChildren
  '/pricing': typeof PricingRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/mobile-dialog': typeof ApiMobileDialogRoute
  '/api/read-message': typeof ApiReadMessageRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/translate-audio': typeof ApiTranslateAudioRoute
  '/api/user-status': typeof ApiUserStatusRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mobile/account': typeof MobileAccountRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/mobile': typeof MobileRouteWithChildren
  '/pricing': typeof PricingRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/mobile-dialog': typeof ApiMobileDialogRoute
  '/api/read-message': typeof ApiReadMessageRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/translate-audio': typeof ApiTranslateAudioRoute
  '/api/user-status': typeof ApiUserStatusRoute
  '/legal/notice': typeof LegalNoticeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mobile/account': typeof MobileAccountRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/mobile'
    | '/pricing'
    | '/api/admin'
    | '/api/mobile-dialog'
    | '/api/read-message'
    | '/api/subscription'
    | '/api/translate-audio'
    | '/api/user-status'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/mobile/account'
    | '/api/public/track-view'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/mobile'
    | '/pricing'
    | '/api/admin'
    | '/api/mobile-dialog'
    | '/api/read-message'
    | '/api/subscription'
    | '/api/translate-audio'
    | '/api/user-status'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/mobile/account'
    | '/api/public/track-view'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/mobile'
    | '/pricing'
    | '/api/admin'
    | '/api/mobile-dialog'
    | '/api/read-message'
    | '/api/subscription'
    | '/api/translate-audio'
    | '/api/user-status'
    | '/legal/notice'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/mobile/account'
    | '/api/public/track-view'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  MobileRoute: typeof MobileRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiMobileDialogRoute: typeof ApiMobileDialogRoute
  ApiReadMessageRoute: typeof ApiReadMessageRoute
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiTranslateAudioRoute: typeof ApiTranslateAudioRoute
  ApiUserStatusRoute: typeof ApiUserStatusRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicTrackViewRoute: typeof ApiPublicTrackViewRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/account': {
      id: '/mobile/account'
      path: '/account'
      fullPath: '/mobile/account'
      preLoaderRoute: typeof MobileAccountRouteImport
      parentRoute: typeof MobileRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/notice': {
      id: '/legal/notice'
      path: '/legal/notice'
      fullPath: '/legal/notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-status': {
      id: '/api/user-status'
      path: '/api/user-status'
      fullPath: '/api/user-status'
      preLoaderRoute: typeof ApiUserStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate-audio': {
      id: '/api/translate-audio'
      path: '/api/translate-audio'
      fullPath: '/api/translate-audio'
      preLoaderRoute: typeof ApiTranslateAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read-message': {
      id: '/api/read-message'
      path: '/api/read-message'
      fullPath: '/api/read-message'
      preLoaderRoute: typeof ApiReadMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-dialog': {
      id: '/api/mobile-dialog'
      path: '/api/mobile-dialog'
      fullPath: '/api/mobile-dialog'
      preLoaderRoute: typeof ApiMobileDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-view': {
      id: '/api/public/track-view'
      path: '/api/public/track-view'
      fullPath: '/api/public/track-view'
      preLoaderRoute: typeof ApiPublicTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MobileRouteChildren {
  MobileAccountRoute: typeof MobileAccountRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileAccountRoute: MobileAccountRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  MobileRoute: MobileRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiMobileDialogRoute: ApiMobileDialogRoute,
  ApiReadMessageRoute: ApiReadMessageRoute,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiTranslateAudioRoute: ApiTranslateAudioRoute,
  ApiUserStatusRoute: ApiUserStatusRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicTrackViewRoute: ApiPublicTrackViewRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
